### ISSUE TITLE
things that work: 0

### ISSUE THREAD

**Issue by Lv-291** [aleeeee1/AnimeStream#1]
# things that work: 0

## Description
When you click any episode of any anime it loads a little and then nothing happens.

## Steps to Reproduce
Do what the app has been designated to do.

## Additional Notes
A template for issues is missing and the back-end is not written in rust.

P.S: I may not have tested with all anime but only with ep 291 of One Piece.

**Comment by aleeeee1** [comment]
Thanks for reporting the issue. 
Animeunity is a fu-
a funny website.

I'll try to fix it today. 
About rust... no

If you want to open a pull request to make an issue template it would be nice!

**Comment by aleeeee1** [comment]
fixed in 386562523f154c3bedb78d60c6d0abb5a0554f42
